services:
  r34sync:
    image: ghcr.io/thalisonnunes20/r34sync-premium:main
    container_name: r34sync_app
    ports:
      - "3000:3000"
    volumes:
      - ./r34_data:/app/data
    environment:
      - DATA_DIR=/app/data
    env_file:
      - .env
    restart: unless-stopped
